[toolchain]
anchor_version = "0.31.0"

[features]
seeds = true
skip-lint = false

[programs.localnet]
vow = "7ytRMwKykiJnbT3gdLXPCUZMzrTNZZbr7m2i7fwiyjbJ"

[programs.testnet]
vow = "7ytRMwKykiJnbT3gdLXPCUZMzrTNZZbr7m2i7fwiyjbJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8980"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
